### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by nipunbatra** [sustainability-lab/vayu#16]
Broadly, we want to use Vayu for all of our use-cases. Every AQ related plot that we make should ideally be supported via Vayu.

Vayu should also be useful for the kinds of plots people working in the AQ domain need to make. This includes plotting related data: such as satellite retrievals, points of interest data, population data, fire count data, etc.

We should have a very simple clean interface which accepts a pd.DataFrame for all of our plots, in additional to optional arguments where necessary.

For each of the issue below, please create a separate issue and edit this issue to mention the newly created issue.

- [ ] Add [jupterbook](https://jupyterbook.org/intro.html) based documentation. With this approach, we only need to create jupyter notebooks and they will suffice for reproducibility and documentation. The jupyerbook should reside as sustainability-lab.github.io/vayu
- [ ] Remove unneeded files, like Report, various .PNG spread across
- [ ] Create an end-to-end example for calendar plot. This should include downloading meterological data (wind speed etc. for IGI Airport New Delhi), we have the corresponding PM data also available via openAQ
- [ ] Each notebook in the documentation should illustrate one and only one functionality
- [ ] Create a package structure. You could have modules like: download (for example: http://davidcarslaw.github.io/openair/#import-data-from-the-uk-automatic-urban-and-rural-network), utils, plots (static, interactive), colormap (we should also have a notebook showing the different colors according to different countries's standards)
- [ ] Discuss with @rishi-a and figure how to plot satellite AQ related data also. That would add a lot of value
- [ ] Discuss with @rishi-a and figure how to use Vayu to plot the KML data we obtain from moving fleet.
- [ ] pip install vayu should also install polire
- [ ] Calendar plot example does not adhere to any colour scheme. See http://indiaairquality.info/wp-content/uploads/anime/pm25_02_WB.png as an example of colour scheme being followed well
- [ ] Plotting choropleth based on shapefile. @prerna-khanna and Tanmay have already done this, though on a shapefile we can not make public. It is recommended to use a publicly available shapefile for some other country along with its AQ and make a choropleth (both static and interactive)
- [ ] Discuss with @rishi-a and figure how to allow plotting the kitchen AQ value heatmap that @rishi-a has prepared.
- [ ] Add a plot on missing data (this in turns calls missingno). See https://github.com/nipunbatra/aq-sat/blob/c6a07540185be8c2224f67219b8a93464d5dba0f/missing-data.ipynb
- [ ] Think about plotting points of interests. Where do we get the data? How can we plot POI with other data (say monitoring stations to make our point)
- [ ] Plot fire data: https://earthdata.nasa.gov/earth-observation-data/near-real-time/firms/active-fire-data
